services:
  gotify:
    image: gotify/server:2.6.1
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8888:80
    env_file:
      - .env
    volumes:
      - gotify_data:/app/data
      - ./plugins/:/app/data/plugins

volumes:
  gotify_data:
    driver: local

